### ISSUE TITLE
Animation: Branch Development

### ISSUE THREAD

**Issue by KevinASaputra** [Bayusetiawan45/v2.codebayu.com#22]
saya sudah coba apply animation di project porto saya tapi kenapa ya untuk animation skillnya waktu berjalan jika sudah habis data  skill yang di tampilin langsung refresh kok tidak teus berjalan aj nyambung dari data atas lagi tanpta refresh jadi seperti konsep `animation tak berkunjung`

**Comment by KevinASaputra** [comment]
Solved, tapi saya pakai [Marquee](https://www.npmjs.com/package/react-fast-marquee), coba pakai ini mas kayanya lebih practice

**Comment by Bayusetiawan45** [comment]
Solved on PR https://github.com/Bayusetiawan45/v2.codebayu.com/pull/25
thanks @KevinASaputra  for your contributions
